version: '2'
services: 
    db:
        image: postgres:9.4
        environment:
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_USER=odoo

    odoo10:
        image: odoo:10.0
        depends_on:
            - db
        ports: 
            - "10000:8069"
        tty: true
        command: -- --dev=reload
        volumes:
            - ./o_addons:/mnt/extra-o_addons
            - ./o_etc:/etc/odoo
volumes:
    db:
    odoo10: